package model

type ErrorCode string

func (e ErrorCode) String() string {
	return string(e)
}

const (
	INVALID_ARGUMENT       ErrorCode = "INVALID_ARGUMENT"
	VALIDATION_ERROR       ErrorCode = "VALIDATION_ERROR"
	FIELD_VALIDATION_ERROR ErrorCode = "FIELD_VALIDATION_ERROR"
	MISSING_REQUIRED_FIELD ErrorCode = "MISSING_REQUIRED_FIELD"
	INVALID_FORMAT         ErrorCode = "INVALID_FORMAT"
	INVALID_REQUEST        ErrorCode = "INVALID_REQUEST"
	INVALID_VALUE          ErrorCode = "INVALID_VALUE"
	OUT_OF_RANGE           ErrorCode = "OUT_OF_RANGE"
	RESOURCE_NOT_FOUND     ErrorCode = "RESOURCE_NOT_FOUND"
	ALREADY_EXISTS         ErrorCode = "ALREADY_EXISTS"
	UNAUTHENTICATED        ErrorCode = "UNAUTHENTICATED"
	UNAUTHORIZED           ErrorCode = "UNAUTHORIZED"
	PERMISSION_DENIED      ErrorCode = "PERMISSION_DENIED"
	ACCESS_DENIED          ErrorCode = "ACCESS_DENIED"
	TOO_MANY_REQUESTS      ErrorCode = "TOO_MANY_REQUESTS"
	RATE_LIMIT_EXCEEDED    ErrorCode = "RATE_LIMIT_EXCEEDED"
	QUOTA_EXCEEDED         ErrorCode = "QUOTA_EXCEEDED"
	INTERNAL_ERROR         ErrorCode = "INTERNAL_ERROR"
	SERVICE_UNAVAILABLE    ErrorCode = "SERVICE_UNAVAILABLE"
	BAD_GATEWAY            ErrorCode = "BAD_GATEWAY"
	MALFORMED_REQUEST      ErrorCode = "MALFORMED_REQUEST"
	UNSUPPORTED_OPERATION  ErrorCode = "UNSUPPORTED_OPERATION"
	PRECONDITION_FAILED    ErrorCode = "PRECONDITION_FAILED"
	RESOURCE_IN_USE        ErrorCode = "RESOURCE_IN_USE"
)
